# Generated by Django 5.2 on 2025-09-06 21:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WhitelistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.CharField(max_length=200, unique=True, verbose_name="采购内容"),
                ),
                (
                    "main_category",
                    models.CharField(
                        choices=[("c2c", "公对公"), ("public", "公共经费")],
                        max_length=20,
                        verbose_name="主分类",
                    ),
                ),
                ("platform", models.CharField(max_length=100, verbose_name="平台/服务")),
                (
                    "purchase_type",
                    models.CharField(
                        choices=[
                            ("consumable", "耗材"),
                            ("chemical", "药品"),
                            ("equipment", "设备"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="采购类型",
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="厂商"
                    ),
                ),
                (
                    "cas_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="CAS号"
                    ),
                ),
                (
                    "product_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="货号"
                    ),
                ),
                (
                    "parameters",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="参数"
                    ),
                ),
                (
                    "specifications",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="规格"
                    ),
                ),
            ],
            options={
                "verbose_name": "白名单项目",
                "verbose_name_plural": "白名单项目",
            },
        ),
        migrations.CreateModel(
            name="PurchaseRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_date",
                    models.DateField(auto_now_add=True, verbose_name="申请日期"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审批"),
                            ("approved", "已批准"),
                            ("rejected", "已驳回"),
                            ("ordered", "已下单"),
                            ("completed", "已完成"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "expense_type",
                    models.CharField(
                        choices=[("c2c", "公对公"), ("public", "公共经费")],
                        max_length=50,
                        verbose_name="经费类型",
                    ),
                ),
                ("platform", models.CharField(max_length=100, verbose_name="平台")),
                (
                    "order_number",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="单号",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="总价"
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请人",
                    ),
                ),
                (
                    "applicant_tutor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请人导师",
                    ),
                ),
            ],
            options={
                "verbose_name": "采购申请",
                "verbose_name_plural": "采购申请",
            },
        ),
        migrations.CreateModel(
            name="RequestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchase_type",
                    models.CharField(
                        choices=[
                            ("consumable", "耗材"),
                            ("chemical", "药品"),
                            ("repair", "维修服务"),
                            ("other", "其他"),
                        ],
                        max_length=50,
                        verbose_name="采购类型",
                    ),
                ),
                ("content", models.CharField(max_length=200, verbose_name="采购内容")),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="厂商"
                    ),
                ),
                (
                    "parameters",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="参数"
                    ),
                ),
                (
                    "cas_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="CAS号"
                    ),
                ),
                (
                    "product_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="货号"
                    ),
                ),
                (
                    "purchase_link",
                    models.URLField(blank=True, null=True, verbose_name="采购链接"),
                ),
                (
                    "specifications",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="规格"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="单价"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="数量")),
                (
                    "purchase_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="procurement.purchaserequest",
                        verbose_name="所属申请",
                    ),
                ),
            ],
            options={
                "verbose_name": "采购物品",
                "verbose_name_plural": "采购物品",
            },
        ),
    ]
