# Generated by Django 5.2 on 2025-09-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0002_purchaserequest_approved_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserequest",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True, verbose_name="驳回原因"),
        ),
    ]
