# Generated by Django 5.2 on 2025-09-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0003_purchaserequest_rejection_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaserequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待审批"),
                    ("approved", "已批准"),
                    ("paid", "已支付"),
                    ("rejected", "已驳回"),
                    ("ordered", "已下单"),
                    ("completed", "已完成"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
