# Generated by Django 5.2 on 2025-09-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0005_alter_purchaserequest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestitem",
            name="purchase_link",
            field=models.TextField(blank=True, null=True, verbose_name="采购链接"),
        ),
    ]
