# Generated by Django 5.2 on 2025-09-20 15:21

from django.db import migrations
import json  # 导入json库


# --- 【修改点 1】定义一个函数，用于转换数据 ---
def convert_main_category_to_list(apps, schema_editor):
    """
    将 WhitelistItem.main_category 的字符串值转换为 JSON 格式的字符串列表。
    例如，将 'c2c' 转换为 '["c2c"]'。
    """
    # 使用 apps.get_model 获取迁移发生时该模型的版本
    WhitelistItem = apps.get_model("procurement", "WhitelistItem")

    # 遍历数据库中所有的 WhitelistItem 对象
    for item in WhitelistItem.objects.all():
        # 确保字段有值且为字符串，防止处理空值或已转换的数据
        if item.main_category and isinstance(item.main_category, str):
            # 将字符串包装在列表中，然后用 json.dumps 转换成 JSON 格式的字符串
            item.main_category = json.dumps([item.main_category])
            # 只更新这一个字段并保存
            item.save(update_fields=["main_category"])


class Migration(migrations.Migration):
    dependencies = [
        ("procurement", "0006_alter_requestitem_purchase_link"),
    ]

    operations = [
        # --- 【修改点 2】在 operations 列表中运行我们上面定义的函数 ---
        migrations.RunPython(convert_main_category_to_list),
    ]