# Generated by Django 5.2 on 2025-09-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0007_convert_category_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaserequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待审批"),
                    ("approved", "已批准"),
                    ("paid", "已支付"),
                    ("rejected", "已驳回"),
                    ("ordered", "已下单"),
                    ("completed", "已完成"),
                    ("withdrawn", "已撤回"),
                    ("payment_rejected", "付款已驳回"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="whitelistitem",
            name="main_category",
            field=models.JSONField(default=list, verbose_name="主分类"),
        ),
    ]
