# Generated by Django 5.2 on 2025-09-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0008_alter_purchaserequest_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="平台名称"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("c2c", "公对公"), ("public", "公共经费")],
                        max_length=20,
                        verbose_name="所属经费类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "采购平台",
                "verbose_name_plural": "采购平台",
                "ordering": ["category", "name"],
            },
        ),
        migrations.AlterField(
            model_name="whitelistitem",
            name="platform",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="平台/服务"
            ),
        ),
    ]
