# Generated by Django 5.2 on 2025-09-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0009_platform_alter_whitelistitem_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="platform",
            name="prefix",
            field=models.CharField(
                blank=True,
                max_length=1,
                null=True,
                unique=True,
                verbose_name="单号前缀(单个大写字母)",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="approval_date",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="批准日期"
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequest",
            name="order_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, unique=True, verbose_name="单号"
            ),
        ),
    ]
