# Generated by Django 5.2 on 2025-09-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0010_platform_prefix_purchaserequest_approval_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaserequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待审批"),
                    ("rejected", "已驳回"),
                    ("withdrawn", "已撤回"),
                    ("payment_rejected", "付款已驳回"),
                    ("approved", "待支付"),
                    ("paid", "待收货"),
                    ("goods_received", "待验收"),
                    ("accepted", "已验收"),
                    ("inspection_skipped", "无需验收"),
                    ("invoiced", "待报销"),
                    ("reimbursed", "已报销"),
                    ("completed", "已完成"),
                    ("ordered", "已下单"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
