# Generated by Django 5.2 on 2025-10-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0011_alter_purchaserequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserequest",
            name="merge_group",
            field=models.UUIDField(
                blank=True, db_index=True, null=True, verbose_name="合并批次ID"
            ),
        ),
        migrations.AlterField(
            model_name="purchaserequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待审批"),
                    ("rejected", "已驳回"),
                    ("withdrawn", "已撤回"),
                    ("payment_rejected", "付款已驳回"),
                    ("approved", "待支付"),
                    ("paid", "待收货"),
                    ("goods_received", "待开票"),
                    ("invoiced", "待验收"),
                    ("accepted", "待报销"),
                    ("inspection_skipped", "待报销 (无需验收)"),
                    ("reimbursed", "已报销"),
                    ("merged", "已合并"),
                    ("completed", "已完成"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
