# Generated by Django 5.2 on 2025-10-04 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0012_purchaserequest_merge_group_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaserequest",
            name="merge_group",
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="parent_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merged_children",
                to="procurement.purchaserequest",
                verbose_name="合并后的父申请",
            ),
        ),
    ]
