# Generated by Django 5.2 on 2025-10-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0013_remove_purchaserequest_merge_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaserequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待审批"),
                    ("rejected", "已驳回"),
                    ("withdrawn", "已撤回"),
                    ("payment_rejected", "付款已驳回"),
                    ("pending_purchase_order", "待请购"),
                    ("pending_contract", "待合同"),
                    ("approved", "待支付"),
                    ("paid", "待收货"),
                    ("goods_received", "待开票"),
                    ("invoiced", "待验收"),
                    ("accepted", "待报销"),
                    ("inspection_skipped", "待报销 (无需验收)"),
                    ("reimbursed", "已报销"),
                    ("merged", "已合并"),
                    ("completed", "已完成"),
                ],
                default="pending",
                max_length=30,
                verbose_name="状态",
            ),
        ),
    ]
