# Generated by Django 5.2 on 2025-10-11 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0015_globalannouncement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="requestitem",
            name="original_applicant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="original_request_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="原始申请人",
            ),
        ),
    ]
