# Generated by Django 5.2 on 2025-10-13 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0016_requestitem_original_applicant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="platform",
            name="managers",
            field=models.ManyToManyField(
                blank=True,
                related_name="managed_platforms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="平台负责人",
            ),
        ),
    ]
