# Generated by Django 5.2 on 2025-10-20 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0017_platform_managers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserequest",
            name="handler",
            field=models.ForeignKey(
                blank=True,
                help_text="记录批准此申请并负责后续流程的用户",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="handled_purchase_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="处理人",
            ),
        ),
    ]
