# Generated by Django 4.2.24 on 2026-04-20 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procurement', '0019_purchaserequest_merge_restore_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicProcurementDutySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_duty', models.JSONField(default=[{'name': '示例成员26', 'weekday': 0}, {'name': '示例成员22', 'weekday': 1}, {'name': '示例成员24', 'weekday': 2}, {'name': '示例成员26', 'weekday': 3}, {'name': '示例成员07', 'weekday': 4}, {'name': '示例成员11', 'weekday': 5}, {'name': '示例成员05', 'weekday': 6}], verbose_name='每周采购人')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '公共经费采购每周采购人设置',
                'verbose_name_plural': '公共经费采购每周采购人设置',
            },
        ),
    ]
