# Generated by Django 4.2.24 on 2026-04-20 15:44

from django.db import migrations, models
import procurement.models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0020_publicprocurementdutyschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicprocurementdutyschedule',
            name='weekly_duty',
            field=models.JSONField(default=procurement.models.default_public_duty_schedule, verbose_name='每周采购人'),
        ),
    ]
