# Generated by Django 5.2 on 2025-09-17 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamPurchaseRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_date",
                    models.DateField(auto_now_add=True, verbose_name="申请日期"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审批"),
                            ("approved", "已批准"),
                            ("rejected", "已驳回"),
                            ("completed", "已完成"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="总价"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, null=True, verbose_name="驳回原因"),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请人",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_approved_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审批人",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属导师",
                    ),
                ),
            ],
            options={
                "verbose_name": "小组请购申请",
                "verbose_name_plural": "小组请购申请",
            },
        ),
        migrations.CreateModel(
            name="TeamRequestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=200, verbose_name="采购内容")),
                (
                    "specifications",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="规格"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="单价"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="数量")),
                (
                    "purchase_link",
                    models.URLField(blank=True, null=True, verbose_name="采购链接(选填)"),
                ),
                (
                    "purchase_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="team_procurement.teampurchaserequest",
                        verbose_name="所属申请",
                    ),
                ),
            ],
            options={
                "verbose_name": "小组采购物品",
                "verbose_name_plural": "小组采购物品",
            },
        ),
    ]
