# Generated by Django 5.2 on 2025-09-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team_procurement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teampurchaserequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待审批"),
                    ("approved", "已批准"),
                    ("rejected", "已驳回"),
                    ("completed", "已完成"),
                    ("withdrawn", "已撤回"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
