# Generated by Django 5.2 on 2025-09-16 15:40

import django.db.models.deletion
import payment.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("procurement", "0004_alter_purchaserequest_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_photo",
                    models.ImageField(
                        upload_to=payment.models.payment_photo_path, verbose_name="支付截图"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="支付时间"),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="支付人",
                    ),
                ),
                (
                    "purchase_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="procurement.purchaserequest",
                        verbose_name="关联的采购申请",
                    ),
                ),
            ],
            options={
                "verbose_name": "支付记录",
                "verbose_name_plural": "支付记录",
            },
        ),
    ]
