# Generated by Django 5.2 on 2025-09-08 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("procurement", "0002_purchaserequest_approved_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Acceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receiving_status", models.TextField(verbose_name="收货情况")),
                (
                    "acceptance_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="acceptances/%Y/%m/%d/",
                        verbose_name="验收照片",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "purchase_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acceptance",
                        to="procurement.purchaserequest",
                        verbose_name="关联的采购申请",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="记录人",
                    ),
                ),
            ],
            options={
                "verbose_name": "收货验收信息",
                "verbose_name_plural": "收货验收信息",
            },
        ),
    ]
