# Generated by Django 5.2 on 2025-09-08 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("procurement", "0002_purchaserequest_approved_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(max_length=255, verbose_name="发票单号"),
                ),
                ("company_name", models.CharField(max_length=255, verbose_name="发票公司")),
                (
                    "invoice_image",
                    models.ImageField(
                        upload_to="invoices/%Y/%m/%d/", verbose_name="发票截图"
                    ),
                ),
                (
                    "requires_acceptance",
                    models.BooleanField(default=False, verbose_name="是否需要验收"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "purchase_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="procurement.purchaserequest",
                        verbose_name="关联的采购申请",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提交人",
                    ),
                ),
            ],
            options={
                "verbose_name": "发票信息",
                "verbose_name_plural": "发票信息",
            },
        ),
    ]
