# Generated by Django 5.2 on 2025-09-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="payment_link",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="付款链接"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_image",
            field=models.ImageField(
                upload_to="invoices/%Y/%M/%d/", verbose_name="发票截图"
            ),
        ),
    ]
