# Generated by Django 5.2 on 2025-10-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0002_invoice_payment_link_alter_invoice_invoice_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_image",
            field=models.ImageField(
                upload_to="invoices/%Y/%m/%d/", verbose_name="发票截图"
            ),
        ),
    ]
