# Generated by Django 5.2 on 2026-01-21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0003_alter_invoice_invoice_image"),
        ("procurement", "0018_purchaserequest_handler"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="purchase_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="procurement.purchaserequest",
                verbose_name="关联的采购申请",
            ),
        ),
    ]

