# Generated by Django 5.2 on 2025-12-15 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DisplayConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "carousel_interval_ms",
                    models.PositiveIntegerField(
                        default=5000,
                        validators=[
                            django.core.validators.MinValueValidator(1000),
                            django.core.validators.MaxValueValidator(60000),
                        ],
                        verbose_name="轮播间隔（毫秒）",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        default="运行正常", max_length=100, verbose_name="当前状态"
                    ),
                ),
                (
                    "tip",
                    models.CharField(
                        default="请保持实验台整洁，离开前确认电源/气源关闭。",
                        max_length=255,
                        verbose_name="今日提示",
                    ),
                ),
                (
                    "safety",
                    models.CharField(
                        default="通风橱使用后请复位；废液按规定分类。",
                        max_length=255,
                        verbose_name="安全检查",
                    ),
                ),
                (
                    "notes",
                    models.JSONField(
                        blank=True, default=list, verbose_name="补充说明（字符串数组）"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "走廊显示配置",
                "verbose_name_plural": "走廊显示配置",
            },
        ),
        migrations.CreateModel(
            name="DisplayImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="corridor_display/images/", verbose_name="图片文件"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="图片名称/备注"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="排序号（越小越靠前）"
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="宽"
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="高"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "走廊显示图片",
                "verbose_name_plural": "走廊显示图片",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
