# Generated by Django 5.2 on 2026-05-13 20:04

import corridor_display.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corridor_display", "0002_displayconfig_duty_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="displayconfig",
            name="lab_duty_groups",
            field=models.JSONField(
                blank=True,
                default=corridor_display.models.default_lab_duty_groups,
                verbose_name="卫生组轮值顺序（字符串数组）",
            ),
        ),
        migrations.AlterField(
            model_name="displayconfig",
            name="package_duty_list",
            field=models.JSONField(
                blank=True,
                default=corridor_display.models.default_package_duty_list,
                verbose_name="取快递值日顺序（字符串数组）",
            ),
        ),
    ]
