# Generated by Django 5.2 on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corridor_display", "0003_alter_displayconfig_lab_duty_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="displayconfig",
            name="duty_rotation_unit",
            field=models.CharField(
                choices=[("week", "按周"), ("day", "按天")], default="week", max_length=4, verbose_name="值日轮换周期"
            ),
        ),
    ]
