# Generated by Django 5.2 on 2025-10-06 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_number",
                    models.CharField(max_length=50, unique=True, verbose_name="项目号"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="项目名")),
                ("description", models.TextField(blank=True, verbose_name="项目说明/公告")),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="发布到首页"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建/修改人",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目管理",
                "verbose_name_plural": "项目管理",
                "ordering": ["-updated_at"],
            },
        ),
    ]
