# Generated by Django 5.2 on 2025-09-28 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("procurement", "0011_alter_purchaserequest_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inspection_number",
                    models.CharField(max_length=255, verbose_name="验收单号"),
                ),
                (
                    "inspection_photo",
                    models.ImageField(
                        upload_to="inspections/%Y/%m/%d/", verbose_name="验收照片"
                    ),
                ),
                (
                    "inspected_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="验收时间"),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="验收人",
                    ),
                ),
                (
                    "purchase_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspection",
                        to="procurement.purchaserequest",
                        verbose_name="关联的采购申请",
                    ),
                ),
            ],
            options={
                "verbose_name": "验收信息",
                "verbose_name_plural": "验收信息",
            },
        ),
    ]
