"""
Django settings for DjangoProject project.

Generated by 'django-admin startproject' using Django 4.2.24.
"""

from pathlib import Path
import os
import pymysql

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_dotenv_file(path):
    if not path.exists():
        return

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue

        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            os.environ.setdefault(key, value)


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.lower() in {"1", "true", "yes", "on"}


def env_list(name, default):
    value = os.getenv(name)
    if not value:
        return default
    return [item.strip() for item in value.split(",") if item.strip()]


load_dotenv_file(BASE_DIR.parent / ".env")
load_dotenv_file(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    raise RuntimeError("Set DJANGO_SECRET_KEY in the environment before starting.")

# === 远程访问加密密钥 ===
# !!! 此密钥绝不能泄露 !!!
# (使用 from cryptography.fernet import Fernet; Fernet.generate_key() 生成)
FERNET_KEY = os.getenv("FERNET_KEY")
if not FERNET_KEY:
    raise RuntimeError("FERNET_KEY is required. Copy .env.example to .env and set a Fernet key.")
# ========================

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", False)

# 允许的主机
# Set explicit hostnames in the deployment environment.
ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", ["localhost", "127.0.0.1"])

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Local Apps
    'users.apps.UsersConfig',
    'procurement.apps.ProcurementConfig',
    'projects.apps.ProjectsConfig',
    'invoice',
    'acceptance',
    'common_serializers',
    'payment',
    'team_procurement',
    'group_affairs',
    'inspection',
    'expense_report',
    'purchase_order',
    'contract',
    'reimbursement',
    'equipment',       # === 新增：仪器与预约模块 ===
    'remote_access',   # === 新增：远程访问模块 ===
    'feedback',
    'labops_agent.apps.LabOpsAgentConfig',

    # === 新增：走廊显示屏模块 ===
    'corridor_display',

    # Third-party Apps
    'rest_framework',
    'corsheaders',
    'django_filters',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "DjangoProject.urls"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'procurement' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = "DjangoProject.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
pymysql.install_as_MySQLdb()

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('MYSQL_DB', 'new_lab_system'),
        'USER': os.getenv('MYSQL_USER', 'root'),
        'PASSWORD': os.getenv('MYSQL_PASSWORD', ''),
        'HOST': os.getenv('MYSQL_HOST', 'localhost'),
        'PORT': os.getenv('MYSQL_PORT', '3306'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
# === 修改后的国际化配置 ===
# 设置为中文，方便后台管理界面显示
LANGUAGE_CODE = "zh-hans"

# 核心修改：设置为北京时间（东八区）
TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

# 保持为 True，让 Django 在数据库存储时使用 UTC，但在显示和过滤时自动转为北京时间
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

CORRIDOR_DISPLAY_PUBLIC_BASE_URL = os.getenv("CORRIDOR_DISPLAY_PUBLIC_BASE_URL", "")


# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS
CORS_ORIGIN_ALLOW_ALL = env_bool("CORS_ORIGIN_ALLOW_ALL", False)

# Custom user model
AUTH_USER_MODEL = 'users.UserProfile'

# DRF
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

# Backend-only LabOps assistant. Disabled unless explicitly enabled in .env.
LABOPS_AGENT = {
    "ENABLED": env_bool("LABOPS_AGENT_ENABLED", False),
    "BASE_URL": os.getenv("LABOPS_LLM_BASE_URL", ""),
    "API_KEY": os.getenv("LABOPS_LLM_API_KEY", ""),
    "MODEL": os.getenv("LABOPS_LLM_MODEL", "gpt-5.6-luna"),
    "TIMEOUT_SECONDS": os.getenv("LABOPS_LLM_TIMEOUT", "30"),
    "MAX_TOOL_ROUNDS": os.getenv("LABOPS_LLM_MAX_TOOL_ROUNDS", "2"),
    "USE_LANGGRAPH": env_bool("LABOPS_AGENT_USE_LANGGRAPH", True),
}

# Optional knowledge retrieval. Keeping this disabled preserves the original
# assistant behavior when Qdrant or the local embedding service is unavailable.
LABOPS_RAG = {
    "ENABLED": env_bool("LABOPS_RAG_ENABLED", False),
    "QDRANT_URL": os.getenv("LABOPS_QDRANT_URL", "http://qdrant:6333"),
    "QDRANT_COLLECTION": os.getenv(
        "LABOPS_QDRANT_COLLECTION", "labops_knowledge_v1"
    ),
    "OLLAMA_URL": os.getenv("LABOPS_OLLAMA_URL", "http://ollama:11434"),
    "EMBEDDING_MODEL": os.getenv("LABOPS_EMBEDDING_MODEL", "bge-m3"),
    "VECTOR_SIZE": os.getenv("LABOPS_RAG_VECTOR_SIZE", "1024"),
    "DENSE_TOP_K": os.getenv("LABOPS_RAG_DENSE_TOP_K", "20"),
    "LEXICAL_TOP_K": os.getenv("LABOPS_RAG_LEXICAL_TOP_K", "20"),
    "FINAL_TOP_K": os.getenv("LABOPS_RAG_FINAL_TOP_K", "4"),
    "MIN_SCORE": os.getenv("LABOPS_RAG_MIN_SCORE", "0.20"),
    "TIMEOUT_SECONDS": os.getenv("LABOPS_RAG_TIMEOUT_SECONDS", "10"),
    "MAX_CONTEXT_CHARS": os.getenv("LABOPS_RAG_MAX_CONTEXT_CHARS", "3000"),
}
