# Generated by Django 5.2 on 2025-11-15 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RdpMachine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="主机名称"),
                ),
                (
                    "ip_address",
                    models.CharField(max_length=100, verbose_name="IP 地址或域名"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="主机描述"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用 (用于预约)"),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Windows 用户名"
                    ),
                ),
                (
                    "encrypted_password",
                    models.CharField(blank=True, max_length=500, verbose_name="加密后的密码"),
                ),
            ],
            options={
                "verbose_name": "远程主机 (含账户)",
                "verbose_name_plural": "远程主机 (含账户)",
            },
        ),
        migrations.CreateModel(
            name="RdpBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "已确认"),
                            ("active", "进行中"),
                            ("completed", "已完成"),
                            ("canceled", "已取消"),
                        ],
                        default="confirmed",
                        max_length=20,
                        verbose_name="预约状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rdp_bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="预约用户",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="remote_access.rdpmachine",
                        verbose_name="预约的主机",
                    ),
                ),
            ],
            options={
                "verbose_name": "远程预约记录",
                "verbose_name_plural": "远程预约记录",
                "ordering": ["-start_time"],
            },
        ),
    ]
