# Generated by Django 5.2 on 2025-11-19 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("remote_access", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rdpbooking",
            name="real_end_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="实际结束时间"),
        ),
        migrations.AddField(
            model_name="rdpbooking",
            name="takeover_applicant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applied_takeovers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="申请插队人",
            ),
        ),
        migrations.AddField(
            model_name="rdpbooking",
            name="takeover_requested_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="申请插队时间"),
        ),
        migrations.AddField(
            model_name="rdpbooking",
            name="takeover_status",
            field=models.CharField(
                choices=[
                    ("none", "无"),
                    ("pending", "等待同意"),
                    ("approved", "已同意"),
                    ("rejected", "已拒绝"),
                ],
                default="none",
                max_length=20,
                verbose_name="插队处理状态",
            ),
        ),
        migrations.AddField(
            model_name="rdpbooking",
            name="termination_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("normal", "主动登出"),
                    ("forced", "超时强制断开"),
                    ("takeover", "被紧急占用"),
                ],
                max_length=20,
                null=True,
                verbose_name="结束原因",
            ),
        ),
    ]
