# Generated by Django 5.2 on 2025-11-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("remote_access", "0002_rdpbooking_real_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rdpmachine",
            name="guacamole_id",
            field=models.IntegerField(
                default=1,
                help_text="请对应 Guacamole 设置中的连接 ID",
                verbose_name="Guacamole连接ID",
            ),
        ),
        migrations.AlterField(
            model_name="rdpmachine",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
    ]
