# Generated by Django 4.2 on 2026-01-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("remote_access", "0003_rdpmachine_guacamole_id_alter_rdpmachine_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="rdpmachine",
            name="device_secret_hash",
            field=models.CharField(blank=True, max_length=128, verbose_name="设备密钥(哈希)"),
        ),
        migrations.AddField(
            model_name="rdpmachine",
            name="device_secret_updated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="密钥更新时间"),
        ),
    ]

