# Generated by Django 4.2 on 2026-01-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("remote_access", "0004_rdpmachine_device_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="rdpmachine",
            name="encrypted_device_secret",
            field=models.CharField(blank=True, max_length=500, verbose_name="设备密钥(加密)"),
        ),
    ]

