# Generated by Django 5.2 on 2025-09-16 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="role",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="roles",
            field=models.ManyToManyField(
                blank=True, to="users.role", verbose_name="角色"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="assigned_tutor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"roles__name": "导师用户"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to=settings.AUTH_USER_MODEL,
                verbose_name="所属导师",
            ),
        ),
    ]
