# Generated by Django 5.2 on 2025-09-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_userprofile_role_userprofile_roles_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="team_procurement_enabled",
            field=models.BooleanField(default=False, verbose_name="启用小组请购"),
        ),
    ]
