# Generated by Django 5.2 on 2025-10-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="contract_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="合同编号"
            ),
        ),
    ]
