# Generated by Django 5.2 on 2025-10-12 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0002_contract_contract_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="contract_number",
        ),
    ]
