# Generated by Django 5.2 on 2025-11-06 07:59

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="仪器名称"),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="放置地点"),
                ),
                ("description", models.TextField(blank=True, verbose_name="说明")),
                (
                    "time_slot_minutes",
                    models.PositiveIntegerField(default=60, verbose_name="时间粒度（分钟）"),
                ),
                (
                    "open_time",
                    models.TimeField(
                        default=datetime.time(8, 0), verbose_name="每日开放开始时间"
                    ),
                ),
                (
                    "close_time",
                    models.TimeField(
                        default=datetime.time(22, 0), verbose_name="每日开放结束时间"
                    ),
                ),
                (
                    "advance_days",
                    models.PositiveIntegerField(default=7, verbose_name="可提前预约天数"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_equipments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "仪器",
                "verbose_name_plural": "仪器",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="预约日期")),
                ("start_time", models.TimeField(verbose_name="开始时间")),
                ("end_time", models.TimeField(verbose_name="结束时间")),
                (
                    "status",
                    models.CharField(
                        choices=[("booked", "已预约"), ("cancelled", "已取消")],
                        default="booked",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="equipment.equipment",
                        verbose_name="仪器",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="预约人",
                    ),
                ),
            ],
            options={
                "verbose_name": "仪器预约",
                "verbose_name_plural": "仪器预约",
                "ordering": ["-date", "-start_time"],
                "indexes": [
                    models.Index(
                        fields=["equipment", "date", "start_time", "end_time"],
                        name="equipment_e_equipme_bba351_idx",
                    )
                ],
            },
        ),
    ]
