# Generated by Django 5.2 on 2025-11-06 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipment",
            name="advance_days",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="close_time",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="open_time",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="time_slot_minutes",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="equipment",
            name="max_advance_days",
            field=models.PositiveSmallIntegerField(default=7, verbose_name="可提前预约天数"),
        ),
        migrations.AddField(
            model_name="equipment",
            name="open_time_end",
            field=models.TimeField(default="22:00", verbose_name="开放结束时间"),
        ),
        migrations.AddField(
            model_name="equipment",
            name="open_time_start",
            field=models.TimeField(default="08:00", verbose_name="开放起始时间"),
        ),
        migrations.AddField(
            model_name="equipment",
            name="time_unit_minutes",
            field=models.PositiveSmallIntegerField(default=60, verbose_name="时间粒度(分钟)"),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="说明"),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="启用"),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="location",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="放置地点"
            ),
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                ("start_time", models.TimeField(verbose_name="开始时间")),
                ("end_time", models.TimeField(verbose_name="结束时间")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "已预约"), ("cancelled", "已取消")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="备注"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="equipment.equipment",
                        verbose_name="仪器",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="预约人",
                    ),
                ),
            ],
            options={
                "verbose_name": "仪器预约",
                "verbose_name_plural": "仪器预约",
                "ordering": ["-date", "start_time"],
            },
        ),
        migrations.DeleteModel(
            name="EquipmentBooking",
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["equipment", "date", "start_time", "end_time"],
                name="equipment_b_equipme_bc2321_idx",
            ),
        ),
    ]
