# Generated by Django 5.2 on 2025-11-13 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0002_remove_equipment_advance_days_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="early_bird_max_advance_days",
            field=models.PositiveSmallIntegerField(
                default=7, help_text="仅对选中的早鸟用户生效；未选择则使用普通天数", verbose_name="早鸟可提前预约天数"
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="early_bird_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="这些用户可以按早鸟天数提前预约此仪器",
                related_name="early_bird_equipments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="早鸟用户",
            ),
        ),
    ]
