# Generated by Django 4.2.11 on 2026-04-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_equipment_ball_mill_rotation_speed_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ballmillqueuerequest',
            new_name='equipment_b_equipme_ceeb60_idx',
            old_name='equipment_b_equipme_3d9b43_idx',
        ),
        migrations.RenameIndex(
            model_name='ballmillqueuerequest',
            new_name='equipment_b_equipme_645f29_idx',
            old_name='equipment_b_equipme_8e065f_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='equipment_b_equipme_ebde13_idx',
            old_name='equipment_window_idx',
        ),
        migrations.AddField(
            model_name='equipment',
            name='electrochemical_offline_channels',
            field=models.JSONField(blank=True, default=list, help_text='仅输力强电化学工作站生效；填写已暂时下线的通道号。', verbose_name='电化学下线通道'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='booking_mode',
            field=models.CharField(choices=[('standard', '普通仪器'), ('planetary_ball_mill', '行星球磨机'), ('electrochemical_workstation', '输力强电化学工作站')], default='standard', max_length=30, verbose_name='预约模式'),
        ),
    ]
