# Generated by Django 5.2 on 2025-09-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="C2CExpenseRecord",
            fields=[
                (
                    "serial_number",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="序号"
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                ("platform", models.CharField(max_length=100, verbose_name="采购平台")),
                (
                    "order_number",
                    models.CharField(max_length=100, unique=True, verbose_name="单号"),
                ),
            ],
            options={
                "verbose_name": "公对公经费统计表",
                "verbose_name_plural": "公对公经费统计表",
            },
        ),
        migrations.CreateModel(
            name="PublicExpenseRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                ("platform", models.CharField(max_length=100, verbose_name="采购平台")),
                (
                    "order_number",
                    models.CharField(max_length=100, unique=True, verbose_name="单号"),
                ),
                (
                    "purchase_link",
                    models.URLField(blank=True, null=True, verbose_name="采购链接"),
                ),
                (
                    "applicant_name",
                    models.CharField(max_length=100, verbose_name="采购申请人"),
                ),
                ("purchase_type", models.CharField(max_length=50, verbose_name="采购类型")),
                ("content", models.CharField(max_length=200, verbose_name="采购内容")),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="厂商"
                    ),
                ),
                (
                    "parameters",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="参数"
                    ),
                ),
                (
                    "specifications",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="规格"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="单价"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="数量")),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="总价"
                    ),
                ),
                ("tutor_name", models.CharField(max_length=100, verbose_name="申请人导师")),
                (
                    "approver_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="审批及采购人姓名"
                    ),
                ),
            ],
            options={
                "verbose_name": "公共经费统计表",
                "verbose_name_plural": "公共经费统计表",
            },
        ),
    ]
