# Generated by Django 5.2 on 2025-11-03 17:55

import django.db.models.deletion
import reimbursement.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0018_purchaserequest_handler"),
        ("reimbursement", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reimbursement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reimbursement_number",
                    models.CharField(
                        help_text="财务系统中的报销单号或凭证号", max_length=100, verbose_name="报销单号"
                    ),
                ),
                (
                    "reimbursement_photo",
                    models.ImageField(
                        upload_to=reimbursement.models.reimbursement_upload_path,
                        verbose_name="报销单照片",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "purchase_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reimbursement_details",
                        to="procurement.purchaserequest",
                        verbose_name="关联的采购申请",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提交人",
                    ),
                ),
            ],
            options={
                "verbose_name": "报销凭证",
                "verbose_name_plural": "报销凭证",
                "ordering": ["-created_at"],
            },
        ),
    ]
